spring.application.name=lastmove
spring.main.web-application-type=none
spring.main.banner-mode=off
logging.level.com.escontrela.lastmove=INFO
spring.datasource.url=jdbc:sqlite:lastmove.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.flyway.enabled=false
lastmove.engine.sunfish.executable=/Users/davidpe/Library/Python/3.9/bin/sunfish-uci
