package com.escontrela.lastmove.application.service;

import com.escontrela.lastmove.application.arena.*;
import com.escontrela.lastmove.application.event.LichessArenaEvent;
import java.time.Instant;
import java.util.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;

/** Long-lived, durable coordinator for outgoing challenges; it is deliberately independent of JavaFX. */
@Service
public final class BotChallengeCycleService {
  private final LichessArenaRepository repository; private final KnightshadeArenaSettingsRepository settings;
  private final LichessBotClient client; private final ApplicationEventPublisher events;
  private volatile List<LichessBotCandidate> bots = List.of(); private volatile Optional<String> botError = Optional.empty();
  public BotChallengeCycleService(LichessArenaRepository repository, KnightshadeArenaSettingsRepository settings, LichessBotClient client, ApplicationEventPublisher events) { this.repository=repository; this.settings=settings; this.client=client; this.events=events; }
  public List<LichessBotCandidate> bots() { return bots; } public Optional<String> botError() { return botError; } public BotChallengeCycle cycle() { return repository.botChallengeCycle(); }
  public synchronized List<LichessBotCandidate> refreshBots() { try { bots=client.onlineBots(token()); botError=Optional.empty(); publish("bots:"+bots.size()); return bots; } catch(RuntimeException failure) { botError=Optional.ofNullable(failure.getMessage()).or(()->Optional.of("Could not load online bots.")); publish(botError.orElse("error")); return bots; } }
  public synchronized BotChallengeCycle start(BotChallengeConfiguration configuration) { if(cycle().active()) throw new IllegalStateException("A bot challenge cycle is already active."); BotChallengeCycle next=new BotChallengeCycle(BotChallengeCycleStatus.DISCOVERING,configuration,List.of(),Optional.empty(),Optional.empty(),Optional.empty(),0,Optional.empty(),Optional.empty(),Instant.now()); save(next); challengeNext(); return cycle(); }
  public synchronized BotChallengeCycle stop() { BotChallengeCycle old=cycle(); if(!old.active()) return old; if(old.currentGameId().isPresent()) { save(with(old,BotChallengeCycleStatus.STOPPING,old.currentBotId(),old.currentChallengeId(),old.currentGameId(),old.completedGames(),old.lastResult(),Optional.of("Stop requested; current game will finish."))); } else { old.currentChallengeId().ifPresent(id->{try{client.cancelChallenge(token(),id);}catch(RuntimeException ignored){}}); save(with(old,BotChallengeCycleStatus.STOPPED,Optional.empty(),Optional.empty(),Optional.empty(),old.completedGames(),old.lastResult(),Optional.of("Stopped by user."))); } return cycle(); }
  public synchronized void onGameStarted(String gameId, Optional<String> challengeId) { onGameStarted(gameId, challengeId, Set.of()); }
  /** Correlates by challenge id when available, otherwise by the selected opponent identity. */
  public synchronized void onGameStarted(String gameId, Optional<String> challengeId, Set<String> playerIds) { BotChallengeCycle old=cycle(); if(!old.active()) return; boolean challengeMatches=old.currentChallengeId().isPresent()&&challengeId.filter(old.currentChallengeId().orElseThrow()::equals).isPresent(); boolean opponentMatches=old.currentBotId().map(expected->playerIds.stream().anyMatch(expected::equalsIgnoreCase)).orElse(false); boolean gameMatches=old.currentGameId().filter(gameId::equals).isPresent(); if(!challengeMatches&&!opponentMatches&&!gameMatches)return; save(with(old,BotChallengeCycleStatus.PLAYING,old.currentBotId(),challengeId.or(()->old.currentChallengeId()),Optional.of(gameId),old.completedGames(),old.lastResult(),Optional.empty())); }
  public synchronized void onChallengeCanceled(String challengeId, String reason) { BotChallengeCycle old=cycle(); if(old.currentChallengeId().filter(challengeId::equals).isEmpty()) return; if(old.status()==BotChallengeCycleStatus.STOPPING) { save(with(old,BotChallengeCycleStatus.STOPPED,Optional.empty(),Optional.empty(),Optional.empty(),old.completedGames(),old.lastResult(),Optional.of("Stopped by user."))); return; } save(with(old,BotChallengeCycleStatus.DISCOVERING,Optional.empty(),Optional.empty(),Optional.empty(),old.completedGames(),old.lastResult(),Optional.of(reason))); challengeNext(); }
  public synchronized void onGameFinished(String gameId, String result) { BotChallengeCycle old=cycle(); if(old.currentGameId().filter(gameId::equals).isEmpty()) return; int completed=old.completedGames()+1; if(old.status()==BotChallengeCycleStatus.STOPPING) { save(with(old,BotChallengeCycleStatus.STOPPED,Optional.empty(),Optional.empty(),Optional.empty(),completed,Optional.of(result),Optional.of("Stopped by user."))); return; } if(completed>=old.configuration().maximumGames()) { save(with(old,BotChallengeCycleStatus.COMPLETED,Optional.empty(),Optional.empty(),Optional.empty(),completed,Optional.of(result),Optional.of("Maximum games reached."))); return; } save(with(old,BotChallengeCycleStatus.DISCOVERING,Optional.empty(),Optional.empty(),Optional.empty(),completed,Optional.of(result),Optional.empty())); challengeNext(); }
  /** Repairs persisted state from Lichess' authoritative active-games and outgoing-challenges views. */
  public synchronized void reconcileRemoteState(Set<String> activeGameIds, Set<String> outgoingChallengeIds) { BotChallengeCycle state=cycle(); if(!state.active()) return; if(state.currentGameId().filter(activeGameIds::contains).isEmpty() && state.currentGameId().isPresent()) { onGameFinished(state.currentGameId().orElseThrow(),"Reconciled after stream interruption"); return; } if(state.currentGameId().isEmpty() && state.currentChallengeId().isPresent() && !outgoingChallengeIds.contains(state.currentChallengeId().orElseThrow())) { onChallengeCanceled(state.currentChallengeId().orElseThrow(),"Challenge is no longer pending on Lichess."); return; } if(state.status()==BotChallengeCycleStatus.ERROR&&state.currentGameId().isEmpty()&&state.currentChallengeId().isEmpty()&&activeGameIds.isEmpty()&&outgoingChallengeIds.isEmpty()) { save(with(state,BotChallengeCycleStatus.DISCOVERING,Optional.empty(),Optional.empty(),Optional.empty(),state.completedGames(),state.lastResult(),Optional.of("Retrying after Lichess reconciliation."))); challengeNext(); } }
  /** Re-enters a persisted active cycle after Lichess streams have reconciled. */
  public synchronized void resume() { BotChallengeCycle state=cycle(); if(!state.active()) return; if(state.status()==BotChallengeCycleStatus.DISCOVERING||state.status()==BotChallengeCycleStatus.CHALLENGING) challengeNext(); else publish(state.status().name()); }
  private void challengeNext() { BotChallengeCycle old=cycle(); if(!old.active()||old.status()==BotChallengeCycleStatus.STOPPING||old.status()==BotChallengeCycleStatus.ERROR) return; if(bots.isEmpty()) refreshBots(); List<LichessBotCandidate> eligible=bots.stream().filter(LichessBotCandidate::available).filter(bot->bot.rating().map(r->r<=old.configuration().maximumOpponentRating()).orElse(false)).filter(bot->!old.currentBotId().filter(id->id.equalsIgnoreCase(bot.id())).isPresent()).toList(); List<LichessBotCandidate> fresh=eligible.stream().filter(bot->!old.attemptedBotIds().contains(bot.id())).toList(); List<LichessBotCandidate> pool=!fresh.isEmpty()?fresh:(old.configuration().allowRepeatWhenExhausted()?eligible:List.of()); if(pool.isEmpty()) { save(with(old,BotChallengeCycleStatus.COMPLETED,Optional.empty(),Optional.empty(),Optional.empty(),old.completedGames(),old.lastResult(),Optional.of("No eligible online bot remains."))); return; } LichessBotCandidate chosen=pool.get(0); List<String> attempted=new ArrayList<>(old.attemptedBotIds()); if(!attempted.contains(chosen.id())) attempted.add(chosen.id()); BotChallengeCycle challenging=new BotChallengeCycle(BotChallengeCycleStatus.CHALLENGING,old.configuration(),attempted,Optional.of(chosen.id()),Optional.empty(),Optional.empty(),old.completedGames(),old.lastResult(),Optional.empty(),Instant.now()); save(challenging); try { LichessChallengeSubmission submission=client.challengeBot(token(),chosen.username(),old.configuration()); BotChallengeCycleStatus status=submission.gameId().isPresent()?BotChallengeCycleStatus.PLAYING:BotChallengeCycleStatus.WAITING_FOR_GAME; save(with(challenging,status,Optional.of(chosen.id()),submission.challengeId(),submission.gameId(),old.completedGames(),old.lastResult(),Optional.empty())); }catch(RuntimeException failure){save(with(challenging,BotChallengeCycleStatus.ERROR,Optional.of(chosen.id()),Optional.empty(),Optional.empty(),old.completedGames(),old.lastResult(),Optional.ofNullable(failure.getMessage())));}}
  private BotChallengeCycle with(BotChallengeCycle old,BotChallengeCycleStatus status,Optional<String> bot,Optional<String> challenge,Optional<String> game,int completed,Optional<String> result,Optional<String> reason){return new BotChallengeCycle(status,old.configuration(),old.attemptedBotIds(),bot,challenge,game,completed,result,reason,Instant.now());}
  private void save(BotChallengeCycle state){repository.saveBotChallengeCycle(state);publish(state.status()+" · "+state.completedGames()+"/"+state.configuration().maximumGames());}
  private String token(){return settings.findBotToken().orElseThrow(()->new IllegalStateException("Configure a Lichess bot token before starting the cycle."));}
  private void publish(String detail){events.publishEvent(new LichessArenaEvent(LichessArenaEvent.Type.BOT_CYCLE_UPDATED,"bot-cycle",detail));}
}
