package com.escontrela.lastmove.application.service;

import com.escontrela.lastmove.application.arena.*;
import com.escontrela.lastmove.application.event.LichessArenaEvent;
import com.fasterxml.jackson.databind.JsonNode;
import jakarta.annotation.PreDestroy;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;

/** Coordinates durable Arena state with Lichess streams. It never treats a closed game stream as a finished game. */
@Service
public final class LichessArenaService {
  private final LichessArenaRepository arena; private final KnightshadeArenaSettingsRepository settings; private final LichessBotClient client; private final ApplicationEventPublisher events;
  @org.springframework.beans.factory.annotation.Autowired(required=false) private LichessArenaTurnService turns;
  private volatile LichessBotClient.StreamHandle accountStream; private final Map<String,LichessBotClient.StreamHandle> gameStreams=new ConcurrentHashMap<>();
  public LichessArenaService(LichessArenaRepository arena,KnightshadeArenaSettingsRepository settings,LichessBotClient client,ApplicationEventPublisher events){this.arena=Objects.requireNonNull(arena);this.settings=Objects.requireNonNull(settings);this.client=Objects.requireNonNull(client);this.events=Objects.requireNonNull(events);}
  public synchronized ArenaConnection connect(){String token=token(); Instant now=Instant.now(); arena.saveConnection(new ArenaConnection(ArenaConnectionStatus.CONNECTING,Optional.empty(),Optional.empty(),Optional.empty(),now)); publish(LichessArenaEvent.Type.CONNECTIVITY_CHANGED,"","Connecting"); close(accountStream); accountStream=client.streamEvents(token,this::onAccountEvent,this::onAccountStreamClosed); ArenaConnection value=new ArenaConnection(ArenaConnectionStatus.CONNECTED,Optional.empty(),Optional.of(now),Optional.empty(),now);arena.saveConnection(value);publish(LichessArenaEvent.Type.CONNECTIVITY_CHANGED,"","Connected"); return value;}
  public synchronized ArenaConnection disconnect(){close(accountStream);accountStream=null;gameStreams.values().forEach(this::close);gameStreams.clear();Instant now=Instant.now();ArenaConnection value=new ArenaConnection(ArenaConnectionStatus.DISCONNECTED,Optional.empty(),arena.connection().connectedAt(),Optional.of(now),now);arena.saveConnection(value);publish(LichessArenaEvent.Type.CONNECTIVITY_CHANGED,"","Disconnected");return value;}
  public ArenaConnection connection(){return arena.connection();} public List<ArenaChallenge> challenges(){return arena.listChallenges();} public List<ArenaGame> activeGames(){return arena.listActiveGames();}
  public Optional<LichessBotAccount> account(){return settings.findValidatedBotAccount();}
  public int maximumConcurrentGames(){return settings.loadSettings().maximumConcurrentGames();}
  public boolean automaticChallengeAcceptance(){return settings.loadSettings().automaticChallengeAcceptance();}
  public void accept(String id){if(!arena.reserveChallenge(id,settings.loadSettings().maximumConcurrentGames())){decide(id,ArenaChallengeDecision.DECLINED,"Maximum concurrent games reached");client.declineChallenge(token(),id,"later");return;}try{client.acceptChallenge(token(),id);decide(id,ArenaChallengeDecision.ACCEPTED,null);}catch(RuntimeException failure){decide(id,ArenaChallengeDecision.FAILED,failure.getMessage());throw failure;}}
  public void decline(String id,String reason){client.declineChallenge(token(),id,reason);decide(id,ArenaChallengeDecision.DECLINED,reason);}
  public void sendMove(String gameId,String uci){client.sendMove(token(),gameId,uci);}
  private void onAccountEvent(JsonNode event){try{switch(event.path("type").asText()){case "challenge"->onChallenge(event.path("challenge"));case "challengeCanceled"->decide(event.path("challenge").path("id").asText(),ArenaChallengeDecision.CANCELED,"Canceled on Lichess");case "gameStart"->startGame(event.path("game"));case "gameFinish"->finishGame(event.path("game").path("id").asText());default->{} }}catch(RuntimeException failure){arena.saveConnection(error(failure));publish(LichessArenaEvent.Type.CONNECTIVITY_CHANGED,"",failure.getMessage());}}
  private void onChallenge(JsonNode node){Instant now=Instant.now();JsonNode challenger=node.path("challenger"),clock=node.path("timeControl");ArenaChallenge value=new ArenaChallenge(node.path("id").asText(),optionalText(challenger,"id"),text(challenger,"name","Unknown"),optionalInt(challenger,"rating"),text(node.path("variant"),"key","standard"),node.path("rated").asBoolean(),optionalInt(clock,"limit"),optionalInt(clock,"increment"),ArenaChallengeDecision.RECEIVED,Optional.empty(),now,Optional.empty(),now);arena.saveChallenge(value);publish(LichessArenaEvent.Type.CHALLENGE_RECEIVED,value.id(),value.challengerName());if(settings.loadSettings().automaticChallengeAcceptance()&&"standard".equalsIgnoreCase(value.variant()))accept(value.id());else if(!"standard".equalsIgnoreCase(value.variant()))decline(value.id(),"Only standard chess is currently supported");}
  private void startGame(JsonNode node){String id=node.path("id").asText();if(id.isBlank())return;Instant now=Instant.now();ArenaGame game=new ArenaGame(id,Optional.empty(),optionalText(node,"challengeId"),optionalText(node,"url"),Optional.empty(),Optional.empty(),Optional.empty(),ArenaGameStatus.STARTED,Optional.empty(),now,Optional.empty(),now);arena.saveGame(game);openGameStream(id);publish(LichessArenaEvent.Type.GAME_STARTED,id,"Started");}
  private void finishGame(String id){if(id.isBlank())return;ArenaGame old=arena.findGame(id).orElse(null);if(old==null)return;Instant now=Instant.now();arena.saveGame(new ArenaGame(old.lichessGameId(),old.localGameId(),old.challengeId(),old.gameUrl(),old.whiteLichessId(),old.blackLichessId(),old.botColor(),ArenaGameStatus.FINISHED,Optional.empty(),old.startedAt(),Optional.of(now),now));publish(LichessArenaEvent.Type.GAME_FINISHED,id,"Finished");}
  private void openGameStream(String gameId){close(gameStreams.put(gameId,client.streamGame(token(),gameId,event->onGameEvent(gameId,event),failure->onGameStreamClosed(gameId,failure))));}
  private void onGameEvent(String id,JsonNode event){ArenaGame old=arena.findGame(id).orElse(null);if(old==null)return;String type=event.path("type").asText();if("gameFull".equals(type)||"gameState".equals(type)){Instant now=Instant.now();ArenaGameStatus status=old.status()==ArenaGameStatus.FINISHED?ArenaGameStatus.FINISHED:ArenaGameStatus.ACTIVE;arena.saveGame(new ArenaGame(old.lichessGameId(),old.localGameId(),old.challengeId(),old.gameUrl(),old.whiteLichessId(),old.blackLichessId(),old.botColor(),status,Optional.empty(),old.startedAt(),old.finishedAt(),now));if(turns!=null){turns.consume(id,event,account().orElseThrow(()->new IllegalStateException("Arena bot account is not validated")),token(),client);turns.localGameId(id).ifPresent(local->arena.saveGame(new ArenaGame(old.lichessGameId(),Optional.of(local),old.challengeId(),old.gameUrl(),old.whiteLichessId(),old.blackLichessId(),old.botColor(),status,Optional.empty(),old.startedAt(),old.finishedAt(),Instant.now())));}publish(LichessArenaEvent.Type.GAME_UPDATED,id,type);}}
  private void onAccountStreamClosed(Throwable failure){if(connection().status()==ArenaConnectionStatus.DISCONNECTED||failure instanceof InterruptedException)return;arena.saveConnection(error(failure));publish(LichessArenaEvent.Type.CONNECTIVITY_CHANGED,"",failure.getMessage());}
  private void onGameStreamClosed(String id,Throwable failure){if(connection().status()==ArenaConnectionStatus.DISCONNECTED||failure instanceof InterruptedException)return;ArenaGame old=arena.findGame(id).orElse(null);if(old==null||old.status()==ArenaGameStatus.FINISHED)return;Instant now=Instant.now();arena.saveGame(new ArenaGame(old.lichessGameId(),old.localGameId(),old.challengeId(),old.gameUrl(),old.whiteLichessId(),old.blackLichessId(),old.botColor(),ArenaGameStatus.STREAM_CLOSED,Optional.ofNullable(failure.getMessage()),old.startedAt(),old.finishedAt(),now));publish(LichessArenaEvent.Type.GAME_UPDATED,id,"Stream closed; reconciliation required");}
  @PreDestroy public void closeOnApplicationExit(){try{disconnect();}catch(RuntimeException ignored){/* Persistence may already be shutting down. */}}
  private void decide(String id,ArenaChallengeDecision decision,String reason){arena.findChallenge(id).ifPresent(old->{Instant now=Instant.now();arena.saveChallenge(new ArenaChallenge(old.id(),old.challengerId(),old.challengerName(),old.challengerRating(),old.variant(),old.rated(),old.clockLimitSeconds(),old.clockIncrementSeconds(),decision,Optional.ofNullable(reason),old.receivedAt(),Optional.of(now),now));publish(LichessArenaEvent.Type.CHALLENGE_DECIDED,id,decision.name());});}
  private ArenaConnection error(Throwable failure){Instant now=Instant.now();return new ArenaConnection(ArenaConnectionStatus.ERROR,Optional.ofNullable(failure.getMessage()).or(()->Optional.of("Lichess stream closed")),arena.connection().connectedAt(),Optional.empty(),now);}private String token(){return settings.findBotToken().orElseThrow(()->new IllegalStateException("Configure a Lichess bot token before connecting Arena."));}private void publish(LichessArenaEvent.Type type,String id,String detail){events.publishEvent(new LichessArenaEvent(type,id,detail));}private void close(LichessBotClient.StreamHandle handle){if(handle!=null)handle.close();}private static String text(JsonNode n,String k,String fallback){String v=n.path(k).asText();return v.isBlank()?fallback:v;}private static Optional<String> optionalText(JsonNode n,String k){String v=n.path(k).asText();return v.isBlank()?Optional.empty():Optional.of(v);}private static Optional<Integer> optionalInt(JsonNode n,String k){return n.hasNonNull(k)?Optional.of(n.path(k).asInt()):Optional.empty();}
}
