package com.escontrela.lastmove.ui.controller;

import com.escontrela.lastmove.application.computer.*;
import com.escontrela.lastmove.application.event.LichessArenaEvent;
import com.escontrela.lastmove.application.repository.SavedGameRepository;
import com.escontrela.lastmove.application.service.*;
import com.escontrela.lastmove.domain.common.PieceColor;
import com.escontrela.lastmove.domain.game.*;
import com.escontrela.lastmove.ui.component.board.ChessBoardControl;
import com.escontrela.lastmove.ui.component.game.*;
import com.escontrela.lastmove.ui.component.message.MessageBox;
import com.escontrela.lastmove.ui.component.notation.*;
import com.escontrela.lastmove.ui.event.*;
import com.escontrela.lastmove.ui.screen.*;
import com.escontrela.lastmove.ui.service.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletionStage;
import javafx.animation.*;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.image.*;
import javafx.scene.layout.StackPane;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Renders an in-memory, live engine-versus-engine game. */
@Component
public class ComputerVsComputerScreenController implements UiScreenController {
  private static final Logger log=LoggerFactory.getLogger(ComputerVsComputerScreenController.class);
  private static final double BOARD_MAX_SIZE=720, ICON=28; private static final String NIGHT="night-mode";
  private final UiFlowManager flow; private final ComputerVsComputerGameService games; private final AnalysisSessionService analysis; private final UiEventBus events; private final ChessSoundService sounds; private final BoardAppearancePreferencesService appearance; private final ComputerEngineSettingsService settings; private final SavedGameRepository savedGames;
  @FXML private StackPane root, boardHost; @FXML private ChessBoardControl chessBoard; @FXML private MoveNotationControl moveNotation; @FXML private ComputerVsComputerSetupOverlay setupOverlay; @FXML private MessageBox resultMessageBox; @FXML private Label opponentPlayerLabel,humanPlayerLabel,opponentClockLabel,humanClockLabel,sourceLabel; @FXML private ImageView opponentPlayerIcon,humanPlayerIcon; @FXML private CapturedPiecesControl opponentCapturedPieces,humanCapturedPieces; @FXML private ThinkingIndicatorControl opponentThinkingIndicator,humanThinkingIndicator; @FXML private TypewriterStatusLabel statusLabel; @FXML private Button takeBackButton,restartButton,resignButton,firstMoveButton,previousMoveButton,nextMoveButton,lastMoveButton; @FXML private javafx.scene.layout.HBox localActions;
  private final Timeline refresh = new Timeline(new KeyFrame(javafx.util.Duration.millis(200), e -> refresh())); private GameId active, lichessLocalGameId; private String lichessGameId; private ComputerVsComputerGameState state; private LiveGameViewerState lichessViewer; private boolean selectingSession,directLichessNavigation,visible,resultShown,following=true; private int reviewed;
  public ComputerVsComputerScreenController(@Lazy UiFlowManager flow, ComputerVsComputerGameService games, AnalysisSessionService analysis, UiEventBus events, ChessSoundService sounds, BoardAppearancePreferencesService appearance, ComputerEngineSettingsService settings, SavedGameRepository savedGames) { this.flow=flow;this.games=games;this.analysis=analysis;this.events=events;this.sounds=sounds;this.appearance=appearance;this.settings=settings;this.savedGames=savedGames; }
  @FXML public void initialize() { root.getProperties().put("controller",this); root.getStyleClass().addListener((javafx.collections.ListChangeListener<String>) c -> icons()); sounds.preload(); chessBoard.setSoundService(sounds); chessBoard.visualEffectsEnabledProperty().bind(appearance.boardVisualEffectsEnabledProperty()); chessBoard.setDisable(true); setupOverlay.setOnCancel(e->backToMain()); setupOverlay.setOnStartGame(e->start(e.configuration())); resultMessageBox.setTitle("Game finished"); resultMessageBox.setAcceptText("Analyze game"); resultMessageBox.setCancelText("Play again"); resultMessageBox.setOnAccept(e->analyze()); resultMessageBox.setOnCancel(e->{resultMessageBox.hide();restart();}); resultMessageBox.setOnClose(e->backToMain()); boardHost.widthProperty().addListener((o,a,b)->size());boardHost.heightProperty().addListener((o,a,b)->size()); refresh.setCycleCount(Animation.INDEFINITE); empty(); }
  @Override public void onShow() { visible=true; if(lichessViewer!=null){if(directLichessNavigation){directLichessNavigation=false;renderLichessViewer();}else chooseLichessOrNewMatch();return;} if (active != null) { try { activate(games.state(active)); return; } catch (NoSuchElementException ignored) { active=null; }} List<ComputerVsComputerGameState> all=games.gamesInMemory(); if (!all.isEmpty()) activate(all.getLast()); else setupOverlay.show(games.availableEngines(), settings::thinkingTime); }
  @Override public void onHide() { visible=false; refresh.stop(); }
  /** Renders an external live session without exposing local-engine lifecycle controls. */
  public void showLichessViewer(String remoteGameId,GameId localGameId, LiveGameViewerState viewer) { directLichessNavigation=true;lichessGameId=Objects.requireNonNull(remoteGameId);lichessLocalGameId=Objects.requireNonNull(localGameId);lichessViewer=Objects.requireNonNull(viewer);log.info("Opening Lichess live viewer: gameId={} localGameId={} plies={}",lichessGameId,lichessLocalGameId,viewer.moves().size());if(visible)renderLichessViewer(); }
  private void chooseLichessOrNewMatch(){selectingSession=true;resultMessageBox.setTitle("Computer vs Computer");resultMessageBox.setMessage("A Lichess Arena game is in progress. Choose what you want to do.");resultMessageBox.setAcceptText("Follow Lichess game");resultMessageBox.setCancelText("New computer match");resultMessageBox.setAdditionalButtonText("Cancel");resultMessageBox.setAdditionalButtonVisible(true);resultMessageBox.setOnAccept(e->{selectingSession=false;resultMessageBox.hide();refreshLichessViewer();});resultMessageBox.setOnCancel(e->{selectingSession=false;resultMessageBox.hide();lichessViewer=null;lichessGameId=null;lichessLocalGameId=null;setupOverlay.show(games.availableEngines(),settings::thinkingTime);});resultMessageBox.setOnAdditionalAction(e->{selectingSession=false;resultMessageBox.hide();flow.show(UiScreenId.MAIN);});resultMessageBox.setOnClose(e->{selectingSession=false;flow.show(UiScreenId.MAIN);});resultMessageBox.show();}
  @org.springframework.context.event.EventListener public void onArenaUpdate(LichessArenaEvent event){if(visible&&lichessLocalGameId!=null&&Objects.equals(lichessGameId,event.externalId())&&event.type()==LichessArenaEvent.Type.GAME_UPDATED){log.info("Lichess viewer received update: gameId={} localGameId={} detail={} selectorVisible={}",event.externalId(),lichessLocalGameId,event.detail(),selectingSession);Platform.runLater(this::refreshLichessViewer);}}
  private void refreshLichessViewer(){savedGames.findSaved(lichessLocalGameId).ifPresentOrElse(saved->{var record=saved.game().toRecord();lichessViewer=new LiveGameViewerState(LiveGameViewerSource.LICHESS,"Lichess Arena",record.whitePlayer().orElseThrow(),record.blackPlayer().orElseThrow(),record.initialPosition(),record.currentPosition(),record.moves().stream().map(RecordedPly::ply).toList(),saved.game().currentClock().whiteRemaining(),saved.game().currentClock().blackRemaining(),record.result().isPresent(),Optional.of("Following Lichess game live"));log.info("Lichess viewer reloaded persisted state: gameId={} localGameId={} plies={} finished={}",lichessGameId,lichessLocalGameId,record.moves().size(),record.result().isPresent());if(!selectingSession)renderLichessViewer();},()->log.warn("Lichess viewer could not find persisted game: gameId={} localGameId={}",lichessGameId,lichessLocalGameId));}
  private void renderLichessViewer() { LiveGameViewerState viewer=Objects.requireNonNull(lichessViewer);
    if (viewer.source()!=LiveGameViewerSource.LICHESS) throw new IllegalArgumentException("Expected a Lichess viewer state");
    refresh.stop(); setupOverlay.hide(); resultMessageBox.hide(); active=null; state=null;
    sourceLabel.setText(viewer.sourceLabel()); localActions.setVisible(false); localActions.setManaged(false);
    chessBoard.renderPosition(viewer.position()); humanPlayerLabel.setText(viewer.whitePlayer().getName()); opponentPlayerLabel.setText(viewer.blackPlayer().getName());
    humanClockLabel.setText(clock(viewer.whiteClock())); opponentClockLabel.setText(clock(viewer.blackClock()));
    moveNotation.setTree(viewer.moves().isEmpty()?List.of():List.of(viewerNode(viewer.moves(),0))); moveNotation.setSelectedNodeId(viewer.moves().isEmpty()?null:viewer.moves().getLast().id()); statusLabel.showImmediately(viewer.message().orElse("Live game from Lichess"));
  }
  private MoveNotationNode viewerNode(List<Ply> moves,int index){Ply ply=moves.get(index);return new MoveNotationNode(new MoveNotationEntry(ply.id(),ply.moveNumber(),ply.movingColor()==PieceColor.WHITE,ply.move().san().getValue(),true),index+1<moves.size()?List.of(viewerNode(moves,index+1)):List.of());}
  @FXML public void backToMain(){ flow.show(UiScreenId.MAIN); }
  @FXML public void resetModel(){ refresh.stop(); if(active!=null) games.closeGame(active); active=null;resultMessageBox.hide();resultShown=false;empty();setupOverlay.show(games.availableEngines(),settings::thinkingTime); }
  @FXML public void resign(){ if(active!=null) apply(games.stop(active)); }
  @FXML public void restart(){ if(active==null)return; GameId old=active;active=null; transition("Restarting game…"); CompletionStage<ComputerVsComputerGameState> job=games.restartGame(old); job.whenComplete((next,failure)->Platform.runLater(()->{if(failure!=null){empty();setupOverlay.show(games.availableEngines(),settings::thinkingTime);setupOverlay.showError(cause(failure));} else activate(next);})); }
  private void start(ComputerVsComputerConfiguration configuration){ setupOverlay.setBusy(true); try { games.createGame(configuration).whenComplete((next,failure)->Platform.runLater(()->{if(failure!=null)setupOverlay.showError(cause(failure));else{setupOverlay.hide();activate(next);}})); } catch(RuntimeException ex){setupOverlay.showError(ex.getMessage());} }
  private void activate(ComputerVsComputerGameState next){ lichessViewer=null;localActions.setVisible(true);localActions.setManaged(true); active=next.gameId();resultShown=false;following=true;reviewed=next.moves().size();chessBoard.setFlipped(false);apply(next);refresh.play(); }
  private void refresh(){if(active==null||!visible)return;try{apply(games.state(active));}catch(RuntimeException ex){refresh.stop();statusLabel.showImmediately(ex.getMessage());}}
  private void apply(ComputerVsComputerGameState next){ state=Objects.requireNonNull(next);if(following)reviewed=state.moves().size();else reviewed=Math.min(reviewed,state.moves().size());chessBoard.renderPosition(position());opponentPlayerLabel.setText(state.blackPlayer().getName());humanPlayerLabel.setText(state.whitePlayer().getName());opponentClockLabel.setText(clock(state.clock().blackRemaining()));humanClockLabel.setText(clock(state.clock().whiteRemaining()));icons();boolean engineThinking=state.phase()==ComputerGamePhase.ENGINE_THINKING;opponentThinkingIndicator.setThinking(engineThinking&&state.position().activeColor()==PieceColor.BLACK);humanThinkingIndicator.setThinking(engineThinking&&state.position().activeColor()==PieceColor.WHITE);statusLabel.showImmediately(turn());notation();captured();takeBackButton.setDisable(true);restartButton.setDisable(false);resignButton.setDisable(state.result().isPresent()||state.stopped());controls();if(state.result().isPresent()||state.stopped()){refresh.stop();showResult();}}
  private void showResult(){if(resultShown)return;resultShown=true;String message;if(state.stopped())message="Game stopped. No winner was declared.";else if(state.result().orElseThrow()==GameResult.DRAW)message="Draw";else message=(state.result().orElseThrow()==GameResult.WHITE_WINS?state.whitePlayer():state.blackPlayer()).getName()+" wins"; String reason=state.terminationReason().map(v->v.name().toLowerCase().replace('_',' ')).orElse("");resultMessageBox.setMessage(message+(reason.isBlank()?".":" by "+reason+"."));resultMessageBox.show();}
  private void analyze(){if(active==null)return;try{var session=analysis.createFromGame(games.gameRecord(active));resultMessageBox.hide();events.publish(new OpenAnalysisSessionEvent(session.sessionId(),"Analyzing engine match: "+session.title()));flow.show(UiScreenId.PGN_ANALYSIS);}catch(RuntimeException ex){statusLabel.showImmediately(cause(ex));}}
  @FXML public void reviewFirstMove(){review(0);}@FXML public void reviewPreviousMove(){review(Math.max(0,reviewed-1));}@FXML public void reviewNextMove(){if(state!=null)review(Math.min(state.moves().size(),reviewed+1));}@FXML public void reviewLastMove(){if(state!=null){following=true;reviewed=state.moves().size();renderReview();}}
  private void review(int count){if(state==null)return;following=count==state.moves().size();reviewed=count;renderReview();} private void renderReview(){chessBoard.renderPosition(position());notation();captured();controls();statusLabel.showImmediately(following?turn():"Reviewing position %d of %d · game continues".formatted(reviewed,state.moves().size()));}
  private void notation(){if(state.moves().isEmpty()){moveNotation.setTree(List.of());moveNotation.setSelectedNodeId(null);return;}moveNotation.setTree(List.of(node(0)));moveNotation.setSelectedNodeId(reviewed==0?null:state.moves().get(reviewed-1).id());} private MoveNotationNode node(int i){Ply ply=state.moves().get(i);return new MoveNotationNode(new MoveNotationEntry(ply.id(),ply.moveNumber(),ply.movingColor()==PieceColor.WHITE,ply.move().san().getValue(),true),i+1<state.moves().size()?List.of(node(i+1)):List.of());}
  private void captured(){List<PositionPiece> pieces=state==null?List.of():state.moves().stream().limit(reviewed).flatMap(p->p.capturedPiece().stream()).toList();humanCapturedPieces.render(pieces.stream().filter(p->p.color()==PieceColor.BLACK).toList());opponentCapturedPieces.render(pieces.stream().filter(p->p.color()==PieceColor.WHITE).toList());}
  private void icons(){if(root==null)return;String color=root.getStyleClass().contains(NIGHT)?"FFFFFF":"000000";opponentPlayerIcon.setImage(engineIcon(state==null?null:state.blackEngine(),color));humanPlayerIcon.setImage(engineIcon(state==null?null:state.whiteEngine(),color));}
  private Image engineIcon(ComputerEngineDescriptor engine,String color){String resource=engine!=null&&ComputerEngineIds.KNIGHTSHADE.equals(engine.id())?(root.getStyleClass().contains(NIGHT)?"/images/knightshade-engine-mark-dark.png":"/images/knightshade-engine-mark.png"):"/images/robot_2_35dp_"+color+".png";return new Image(Objects.requireNonNull(getClass().getResource(resource)).toExternalForm());}
  private void empty(){state=null;opponentPlayerLabel.setText("Black engine");humanPlayerLabel.setText("White engine");opponentClockLabel.setText("--:--");humanClockLabel.setText("--:--");statusLabel.showImmediately("Choose both engines and a time control");moveNotation.setTree(List.of());opponentCapturedPieces.render(List.of());humanCapturedPieces.render(List.of());takeBackButton.setDisable(true);restartButton.setDisable(true);resignButton.setDisable(true);opponentThinkingIndicator.setThinking(false);humanThinkingIndicator.setThinking(false);reviewed=0;following=true;icons();controls();}
  private void controls(){boolean none=state==null;int size=none?0:state.moves().size();firstMoveButton.setDisable(none||reviewed==0);previousMoveButton.setDisable(none||reviewed==0);nextMoveButton.setDisable(none||reviewed>=size);lastMoveButton.setDisable(none||following);}
  private void transition(String text){refresh.stop();statusLabel.showImmediately(text);restartButton.setDisable(true);resignButton.setDisable(true);}
  private void size(){double available=Math.min(boardHost.getWidth(),boardHost.getHeight());if(available>0)chessBoard.setPrefSize(Math.min(available,BOARD_MAX_SIZE),Math.min(available,BOARD_MAX_SIZE));}
  private PositionSnapshot position(){return reviewed==0?state.initialPosition():state.moves().get(reviewed-1).resultingPosition();} private String turn(){if(state==null)return "";if(state.stopped())return "Game stopped";return switch(state.phase()){case STARTING->"Starting engines…";case ENGINE_THINKING->(state.position().activeColor()==PieceColor.WHITE?state.whiteEngine():state.blackEngine()).displayName()+" is thinking…";case FINISHED->"Game finished";case ENGINE_ERROR->state.message().orElse("Computer engine error");case WAITING_FOR_HUMAN->"Waiting";};} private static String clock(Optional<Duration> value){if(value.isEmpty())return "∞";long s=Math.max(0,value.orElseThrow().toSeconds());return "%02d:%02d".formatted(s/60,s%60);}private static String cause(Throwable t){while(t.getCause()!=null)t=t.getCause();return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
}
